### ISSUE TITLE
Can not show.py

### ISSUE THREAD

**Issue by sounansu** [RolandGao/RegSeg#6]
I try show.py.
But I can not.

```
$ python3 show.py
name= cityscapes
train size: 2975
val size: 500
Traceback (most recent call last):
  File "show.py", line 358, in <module>
    show_cityscapes_model()
  File "show.py", line 337, in show_cityscapes_model
    show(model,val_loader,device,show_cityscapes_mask,num_images=num_images,skip=skip,images_per_line=images_per_line)
  File "show.py", line 134, in show
    outputs = model(images)
  File "/home/sounansu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sounansu/RegSeg/model.py", line 76, in forward
    x=self.stem(x)
  File "/home/sounansu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sounansu/RegSeg/blocks.py", line 22, in forward
    x = self.conv(x)
  File "/home/sounansu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sounansu/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/sounansu/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
```

**Comment by RolandGao** [comment]
Can you git pull and try again? I made some changes.

**Comment by sounansu** [comment]
Thank You!  RolandGao.
I can do show.py, and pop up this windows.

![screenshot](https://user-images.githubusercontent.com/14190013/147341408-073c7f73-0a68-4ffe-93dd-1fdcd2b4a8cc.png)
